---

- name: Install Supervisor
  apt: pkg=supervisor state=present

- name: Create supervisior path
  file: path=/etc/supervisor/conf.d state=directory owner=root mode=0755 recurse=yes
  sudo: yes

- name: Setup supervisor configuration
  template: src=supervisor.conf.j2 dest=/etc/supervisor/conf.d/{{ app.name }}-{{ item.connection }}.conf owner=root mode=0755
  with_items: supervisor.connections

- name: Add supervisor configuration
  supervisorctl: name="{{ app.name }}-{{ item.connection }}:*" state=started config=/etc/supervisor/conf.d/{{ app.name }}-{{ item.connection }}.conf
  with_items: supervisor.connections

- name: Reread supervisor configuration
  shell: "sudo supervisorctl reread"

- name: Update supervisor configuration
  shell: "sudo supervisorctl update"

- name: Start supervisor configuration
  shell: "sudo supervisorctl start {{ app.name }}-{{ item.connection }}:*"
  with_items: supervisor.connections


- name: Restart supervisor configuration
  shell: "sudo supervisorctl restart {{ app.name }}-{{ item.connection }}:*"
  with_items: supervisor.connections

- name: Enable Supervisor
  service: name=supervisor state=started enabled=yes

- name: Schedule Restart on the Workers
  cron: name="restart workers" minute="0" hour="0" state="present" job="supervisorctl restart {{ app.name }}-{{ item.connection }}:*"
  with_items: supervisor.connections
  sudo: yes
